#! /bin/sh

sxhkd &

# if [[ $(hostname) == 'arch-desktop' ]]; then
#     xrandr --output HDMI-0 --primary --left-of DVI-I-0
#     bspc monitor HDMI-0 -d I II III IV V 
#     bspc monitor DVI-I-0 -d VI VII VIII IX X
# elif [[ $(hostname) == 'arch' ]]; then
#     xinput set-prop 11 289 1
#     bspc monitor -d I II III IV V VI
# else
#     bspc monitor -d I II III IV V VI VII VIII IX X
# fi

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width            5
bspc config window_gap              12
bspc config top_padding             20
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config border_radius           10
bspc config presel_feedback_color   "#969696"
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer   true
bspc config click_to_focus          true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Slack desktop='^3'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=o
# bspc rule -a Screenkey manage=off

python ~/.local/lib/python2.7/site-packages/mopidy &

killall alacritty && alacritty --name quake &
killall volumeicon && volumeicon &
nextcloud &
nm-applet &
killall greenclip && greenclip daemon &
dunst &
killall compton && compton --config ~/.config/i3/compton.conf &
xautolock -time 6 -locker "i3-blur-lock --dpms" &
i3-polybar &
killall redshift && redshift -l 48.15:11.64 &
bash -c "sleep 2 && i3-autostart" &
xinput --set-prop $(xinput |grep -oP "TouchPad.*id=\K[0-9]+")  "libinput Natural Scrolling Enabled" 1 &
feh --bg-fill ~/Pictures/Wallpapers/mountains-valley.jpg &

bspc config top_padding 23
bspc config right_padding -6
bspc config left_padding -6
bspc config bottom_padding 3

