#! /bin/sh

sxhkd &
xrdb -merge ~/.Xresources


if [[ "$HOSTNAME" == "zog"* ]]; then
    bspc monitor %DP-2 -d work web docs media files graphics
    bspc monitor %DP-3.8 -d comm dump
else
    bspc monitor -d work web comm docs media files graphics dump
fi

bspc config border_width            2
bspc config window_gap              10
bspc config top_padding             34
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config border_radius           10
bspc config normal_border_color     "#7f8c8d"
bspc config active_border_color     "#c065db"
bspc config focused_border_color    "#1ABC9C"
bspc config presel_feedback_color   "#9B59B6"
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer   true
bspc config click_to_focus          true

bspc rule -a Slack desktop='comm'
bspc rule -a Vivaldi desktop='comm'
bspc rule -a pcmanfm state=floating

i3-autostart &
numlockx on
