#!/bin/bash

sxhkd &

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width            2
bspc config window_gap              10
bspc config top_padding             34
bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config gapless_monocle         true
bspc config right_monocle_padding   200
bspc config left_monocle_padding    200
bspc config border_radius           10
bspc config normal_border_color     "#7f8c8d"
bspc config active_border_color     "#c065db"
bspc config focused_border_color    "#1ABC9C"
bspc config presel_feedback_color   "#9B59B6"
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer   true
bspc config click_to_focus          true

bspc rule -a Slack desktop='comm'
bspc rule -a Emacs desktop='docs' state='pseudo_tiled'
#bspc rule -a Firefox desktop='web'
bspc rule -a vivaldi-stable desktop='comm'
bspc rule -a pcmanfm state=floating
bspc rule -a Nautilus state=floating
bspc config external_rules_command ~/.config/bspwm/external_rules
i3-autostart &
