source ~/.config/environment.d/*
export PATH
export DICPATH
export XDG_CURRENT_DESKTOP
export PASSWORD_STORE_DIR
export MOZ_ENABLE_WAYLAND
export MOZ_USE_XINPUT2
export VAGRANT_DEFAULT_PROVIDER=libvirt
export VAGRANT_DOTFILE_PATH=".vagrant-$(hostname)"
export QT_QPA_PLATFORMTHEME="qt5ct"
