name: release
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
    - name: Update new version for plugin 'ctx' in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.31
      with:
        krew_template_file: .krew/ctx.yaml
    - name: Update new version for plugin 'ns' in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.31
      with:
        krew_template_file: .krew/ns.yaml 


