[icons]
icons = "awesome6"

[theme]
theme = "plain"

[theme.overrides]
idle_bg = "#2E3440"
good_bg = "#2E3440"
warning_bg = "#81A1C1"
critical_bg = "#88C0D0"
separator_bg = "#2E3440"
separator_fg = "#434C5E"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:'u%R') "
timezone = "UTC"

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%d/%m %R', l:de_DE) "
timezone = "Europe/Berlin"
